import os

print("Stoping h1...")
os.system("docker container stop h1")
print("Stoping h2...")
os.system("docker container stop h2")
print("Stoping BRG1...")
os.system("docker container stop BRG1")
print("Stoping BRG2...")
os.system("docker container stop BRG2")
print("Stoping BRGr...")
os.system("docker container stop BRGr")
print("Stoping edge...")
os.system("docker container stop edge")
print("Stoping r1...")
os.system("docker container stop r1")
print("Removing br0...")
os.system("ip link set br0 down")
os.system("ip link delete br0 type bridge")
print("Removing host NAT rules...")
os.system("iptables -t nat -D POSTROUTING 1")
os.system("kill -9 `ps aux | grep veth | grep dhcpd | awk '{print $2}'`")